// Code generated by murmur-codegen-typed. DO NOT EDIT.
// Source: pipeline-spec for service BotInteractionCountService.

package v1

import (
	"context"
	"fmt"
	"strings"
	"time"

	"connectrpc.com/connect"

	"github.com/gallowaysoftware/murmur/pkg/query/typed"
	"github.com/gallowaysoftware/murmur/proto/gen/murmur/v1/murmurv1connect"

	pb "github.com/example/count-core/gen/bot/v1"
)

// BotInteractionCountServiceServer is the typed Connect-RPC server for the
// "bot_interactions" Murmur pipeline.
type BotInteractionCountServiceServer struct {
	client *typed.SumClient
}

// NewBotInteractionCountServiceServer constructs the server given a Connect-RPC
// client to the Murmur QueryService backing the
// "bot_interactions" pipeline.
func NewBotInteractionCountServiceServer(murmur murmurv1connect.QueryServiceClient) *BotInteractionCountServiceServer {
	return &BotInteractionCountServiceServer{
		client: typed.NewSumClient(murmur),
	}
}

// GetCount implements the GetCount RPC.
func (s *BotInteractionCountServiceServer) GetCount(ctx context.Context, req *connect.Request[pb.GetCountRequest]) (*connect.Response[pb.GetCountResponse], error) {
	msg := req.Msg
	if strings.TrimSpace(msg.BotId) == "" {
		return nil, connect.NewError(connect.CodeInvalidArgument, fmt.Errorf("bot_id is required"))
	}
	if strings.TrimSpace(msg.UserId) == "" {
		return nil, connect.NewError(connect.CodeInvalidArgument, fmt.Errorf("user_id is required"))
	}
	key := fmt.Sprintf("bot:%s|user:%s", msg.BotId, msg.UserId)
	val, present, err := s.client.Get(ctx, key)
	if err != nil {
		return nil, connect.NewError(connect.CodeInternal, err)
	}
	return connect.NewResponse(&pb.GetCountResponse{
		Value:   val,
		Present: present,
	}), nil
}

// GetCountWindow implements the GetCountWindow RPC.
func (s *BotInteractionCountServiceServer) GetCountWindow(ctx context.Context, req *connect.Request[pb.GetCountWindowRequest]) (*connect.Response[pb.GetCountWindowResponse], error) {
	msg := req.Msg
	if strings.TrimSpace(msg.BotId) == "" {
		return nil, connect.NewError(connect.CodeInvalidArgument, fmt.Errorf("bot_id is required"))
	}
	if strings.TrimSpace(msg.UserId) == "" {
		return nil, connect.NewError(connect.CodeInvalidArgument, fmt.Errorf("user_id is required"))
	}
	key := fmt.Sprintf("bot:%s|user:%s", msg.BotId, msg.UserId)
	duration := time.Duration(msg.DurationSeconds) * time.Second
	val, err := s.client.GetWindow(ctx, key, duration)
	if err != nil {
		return nil, connect.NewError(connect.CodeInternal, err)
	}
	return connect.NewResponse(&pb.GetCountWindowResponse{
		Value:   val,
		Present: true,
	}), nil
}
