// Code generated by murmur-codegen-typed. DO NOT EDIT.
// Source: pipeline-spec for service BotInteractionCountService.

package v1

import (
	"context"
	"fmt"
	"strings"
	"time"

	"connectrpc.com/connect"

	"github.com/gallowaysoftware/murmur/pkg/query/typed"
	"github.com/gallowaysoftware/murmur/proto/gen/murmur/v1/murmurv1connect"

	pb "github.com/example/count-core/gen/bot/v1"
)

// BotInteractionCountServiceServer is the typed Connect-RPC server for the
// "bot_interactions" Murmur pipeline.
type BotInteractionCountServiceServer struct {
	client *typed.SumClient
}

// NewBotInteractionCountServiceServer constructs the server given a Connect-RPC
// client to the Murmur QueryService backing the
// "bot_interactions" pipeline.
func NewBotInteractionCountServiceServer(murmur murmurv1connect.QueryServiceClient) *BotInteractionCountServiceServer {
	return &BotInteractionCountServiceServer{
		client: typed.NewSumClient(murmur),
	}
}

// GetCount implements the GetCount RPC.
func (s *BotInteractionCountServiceServer) GetCount(ctx context.Context, req *connect.Request[pb.GetCountRequest]) (*connect.Response[pb.GetCountResponse], error) {
	msg := req.Msg
	if strings.TrimSpace(msg.BotId) == "" {
		return nil, connect.NewError(connect.CodeInvalidArgument, fmt.Errorf("bot_id is required"))
	}
	if strings.TrimSpace(msg.UserId) == "" {
		return nil, connect.NewError(connect.CodeInvalidArgument, fmt.Errorf("user_id is required"))
	}
	key := fmt.Sprintf("bot:%s|user:%s", msg.BotId, msg.UserId)
	val, present, err := s.client.Get(ctx, key)
	if err != nil {
		return nil, connect.NewError(connect.CodeInternal, err)
	}
	return connect.NewResponse(&pb.GetCountResponse{
		Value:   val,
		Present: present,
	}), nil
}

// GetCountWindow implements the GetCountWindow RPC.
func (s *BotInteractionCountServiceServer) GetCountWindow(ctx context.Context, req *connect.Request[pb.GetCountWindowRequest]) (*connect.Response[pb.GetCountWindowResponse], error) {
	msg := req.Msg
	if strings.TrimSpace(msg.BotId) == "" {
		return nil, connect.NewError(connect.CodeInvalidArgument, fmt.Errorf("bot_id is required"))
	}
	if strings.TrimSpace(msg.UserId) == "" {
		return nil, connect.NewError(connect.CodeInvalidArgument, fmt.Errorf("user_id is required"))
	}
	key := fmt.Sprintf("bot:%s|user:%s", msg.BotId, msg.UserId)
	duration := time.Duration(msg.DurationSeconds) * time.Second
	val, err := s.client.GetWindow(ctx, key, duration)
	if err != nil {
		return nil, connect.NewError(connect.CodeInternal, err)
	}
	return connect.NewResponse(&pb.GetCountWindowResponse{
		Value:   val,
		Present: true,
	}), nil
}

// GetCountWindowMany implements the GetCountWindowMany RPC.
func (s *BotInteractionCountServiceServer) GetCountWindowMany(ctx context.Context, req *connect.Request[pb.GetCountWindowManyRequest]) (*connect.Response[pb.GetCountWindowManyResponse], error) {
	msg := req.Msg
	if strings.TrimSpace(msg.BotId) == "" {
		return nil, connect.NewError(connect.CodeInvalidArgument, fmt.Errorf("bot_id is required"))
	}
	if len(msg.UserIds) == 0 {
		return nil, connect.NewError(connect.CodeInvalidArgument, fmt.Errorf("user_ids is required"))
	}
	duration := time.Duration(msg.DurationSeconds) * time.Second
	keys := make([]string, len(msg.UserIds))
	for i, v := range msg.UserIds {
		keys[i] = fmt.Sprintf("bot:%s|user:%s", msg.BotId, v)
	}
	values, err := s.client.GetWindowMany(ctx, keys, duration)
	if err != nil {
		return nil, connect.NewError(connect.CodeInternal, err)
	}
	return connect.NewResponse(&pb.GetCountWindowManyResponse{
		Values: values,
	}), nil
}

// GetCountMany implements the GetCountMany RPC.
func (s *BotInteractionCountServiceServer) GetCountMany(ctx context.Context, req *connect.Request[pb.GetCountManyRequest]) (*connect.Response[pb.GetCountManyResponse], error) {
	msg := req.Msg
	if strings.TrimSpace(msg.BotId) == "" {
		return nil, connect.NewError(connect.CodeInvalidArgument, fmt.Errorf("bot_id is required"))
	}
	if len(msg.UserIds) == 0 {
		return nil, connect.NewError(connect.CodeInvalidArgument, fmt.Errorf("user_ids is required"))
	}
	keys := make([]string, len(msg.UserIds))
	for i, v := range msg.UserIds {
		keys[i] = fmt.Sprintf("bot:%s|user:%s", msg.BotId, v)
	}
	values, present, err := s.client.GetMany(ctx, keys)
	if err != nil {
		return nil, connect.NewError(connect.CodeInternal, err)
	}
	return connect.NewResponse(&pb.GetCountManyResponse{
		Values:  values,
		Present: present,
	}), nil
}

// GetCountRange implements the GetCountRange RPC.
func (s *BotInteractionCountServiceServer) GetCountRange(ctx context.Context, req *connect.Request[pb.GetCountRangeRequest]) (*connect.Response[pb.GetCountRangeResponse], error) {
	msg := req.Msg
	if strings.TrimSpace(msg.BotId) == "" {
		return nil, connect.NewError(connect.CodeInvalidArgument, fmt.Errorf("bot_id is required"))
	}
	if strings.TrimSpace(msg.UserId) == "" {
		return nil, connect.NewError(connect.CodeInvalidArgument, fmt.Errorf("user_id is required"))
	}
	key := fmt.Sprintf("bot:%s|user:%s", msg.BotId, msg.UserId)
	start := time.Unix(msg.StartUnix, 0)
	end := time.Unix(msg.EndUnix, 0)
	val, err := s.client.GetRange(ctx, key, start, end)
	if err != nil {
		return nil, connect.NewError(connect.CodeInternal, err)
	}
	return connect.NewResponse(&pb.GetCountRangeResponse{
		Value: val,
	}), nil
}
