// Code generated by murmur-codegen-typed. DO NOT EDIT.
// Source: pipeline-spec for service TopProductsService.

package v1

import (
	"context"
	"fmt"
	"strings"
	"time"

	"connectrpc.com/connect"

	"github.com/gallowaysoftware/murmur/pkg/query/typed"
	"github.com/gallowaysoftware/murmur/proto/gen/murmur/v1/murmurv1connect"

	pb "github.com/example/storefront/gen/products/v1"
)

// TopProductsServiceServer is the typed Connect-RPC server for the
// "products_topk" Murmur pipeline.
type TopProductsServiceServer struct {
	client *typed.TopKClient
}

// NewTopProductsServiceServer constructs the server given a Connect-RPC
// client to the Murmur QueryService backing the
// "products_topk" pipeline.
func NewTopProductsServiceServer(murmur murmurv1connect.QueryServiceClient) *TopProductsServiceServer {
	return &TopProductsServiceServer{
		client: typed.NewTopKClient(murmur),
	}
}

// GetTop implements the GetTop RPC.
func (s *TopProductsServiceServer) GetTop(ctx context.Context, req *connect.Request[pb.GetTopRequest]) (*connect.Response[pb.GetTopResponse], error) {
	msg := req.Msg
	if strings.TrimSpace(msg.CategoryId) == "" {
		return nil, connect.NewError(connect.CodeInvalidArgument, fmt.Errorf("category_id is required"))
	}
	key := fmt.Sprintf("category:%s", msg.CategoryId)
	val, present, err := s.client.Get(ctx, key)
	if err != nil {
		return nil, connect.NewError(connect.CodeInternal, err)
	}
	items := make([]*pb.TopKItem, len(val))
	for i, it := range val {
		items[i] = &pb.TopKItem{Key: it.Key, Count: int64(it.Count)}
	}
	return connect.NewResponse(&pb.GetTopResponse{
		Items:   items,
		Present: present,
	}), nil
}

// GetTopWindow implements the GetTopWindow RPC.
func (s *TopProductsServiceServer) GetTopWindow(ctx context.Context, req *connect.Request[pb.GetTopWindowRequest]) (*connect.Response[pb.GetTopWindowResponse], error) {
	msg := req.Msg
	if strings.TrimSpace(msg.CategoryId) == "" {
		return nil, connect.NewError(connect.CodeInvalidArgument, fmt.Errorf("category_id is required"))
	}
	key := fmt.Sprintf("category:%s", msg.CategoryId)
	duration := time.Duration(msg.DurationSeconds) * time.Second
	val, err := s.client.GetWindow(ctx, key, duration)
	if err != nil {
		return nil, connect.NewError(connect.CodeInternal, err)
	}
	items := make([]*pb.TopKItem, len(val))
	for i, it := range val {
		items[i] = &pb.TopKItem{Key: it.Key, Count: int64(it.Count)}
	}
	return connect.NewResponse(&pb.GetTopWindowResponse{
		Items:   items,
		Present: true,
	}), nil
}
