// Code generated by murmur-codegen-typed. DO NOT EDIT.
// Source: pipeline-spec for service TopProductsService.

package v1

import (
	"context"
	"fmt"
	"strings"
	"time"

	"connectrpc.com/connect"

	"github.com/gallowaysoftware/murmur/pkg/query/typed"
	"github.com/gallowaysoftware/murmur/proto/gen/murmur/v1/murmurv1connect"

	pb "github.com/example/storefront/gen/products/v1"
)

// TopProductsServiceServer is the typed Connect-RPC server for the
// "products_topk" Murmur pipeline.
type TopProductsServiceServer struct {
	client *typed.TopKClient
}

// NewTopProductsServiceServer constructs the server given a Connect-RPC
// client to the Murmur QueryService backing the
// "products_topk" pipeline.
func NewTopProductsServiceServer(murmur murmurv1connect.QueryServiceClient) *TopProductsServiceServer {
	return &TopProductsServiceServer{
		client: typed.NewTopKClient(murmur),
	}
}

// GetTop implements the GetTop RPC.
func (s *TopProductsServiceServer) GetTop(ctx context.Context, req *connect.Request[pb.GetTopRequest]) (*connect.Response[pb.GetTopResponse], error) {
	msg := req.Msg
	if strings.TrimSpace(msg.CategoryId) == "" {
		return nil, connect.NewError(connect.CodeInvalidArgument, fmt.Errorf("category_id is required"))
	}
	key := fmt.Sprintf("category:%s", msg.CategoryId)
	val, present, err := s.client.Get(ctx, key)
	if err != nil {
		return nil, connect.NewError(connect.CodeInternal, err)
	}
	items := make([]*pb.TopKItem, len(val))
	for i, it := range val {
		items[i] = &pb.TopKItem{Key: it.Key, Count: int64(it.Count)}
	}
	return connect.NewResponse(&pb.GetTopResponse{
		Items:   items,
		Present: present,
	}), nil
}

// GetTopWindow implements the GetTopWindow RPC.
func (s *TopProductsServiceServer) GetTopWindow(ctx context.Context, req *connect.Request[pb.GetTopWindowRequest]) (*connect.Response[pb.GetTopWindowResponse], error) {
	msg := req.Msg
	if strings.TrimSpace(msg.CategoryId) == "" {
		return nil, connect.NewError(connect.CodeInvalidArgument, fmt.Errorf("category_id is required"))
	}
	key := fmt.Sprintf("category:%s", msg.CategoryId)
	duration := time.Duration(msg.DurationSeconds) * time.Second
	val, err := s.client.GetWindow(ctx, key, duration)
	if err != nil {
		return nil, connect.NewError(connect.CodeInternal, err)
	}
	items := make([]*pb.TopKItem, len(val))
	for i, it := range val {
		items[i] = &pb.TopKItem{Key: it.Key, Count: int64(it.Count)}
	}
	return connect.NewResponse(&pb.GetTopWindowResponse{
		Items:   items,
		Present: true,
	}), nil
}

// GetTopWindowMany implements the GetTopWindowMany RPC.
func (s *TopProductsServiceServer) GetTopWindowMany(ctx context.Context, req *connect.Request[pb.GetTopWindowManyRequest]) (*connect.Response[pb.GetTopWindowManyResponse], error) {
	msg := req.Msg
	if len(msg.CategoryIds) == 0 {
		return nil, connect.NewError(connect.CodeInvalidArgument, fmt.Errorf("category_ids is required"))
	}
	duration := time.Duration(msg.DurationSeconds) * time.Second
	keys := make([]string, len(msg.CategoryIds))
	for i, v := range msg.CategoryIds {
		keys[i] = fmt.Sprintf("category:%s", v)
	}
	values, err := s.client.GetWindowMany(ctx, keys, duration)
	if err != nil {
		return nil, connect.NewError(connect.CodeInternal, err)
	}
	entries := make([]*pb.TopKItemList, len(values))
	for i, v := range values {
		items := make([]*pb.TopKItem, len(v))
		for j, it := range v {
			items[j] = &pb.TopKItem{Key: it.Key, Count: int64(it.Count)}
		}
		entries[i] = &pb.TopKItemList{Items: items}
	}
	return connect.NewResponse(&pb.GetTopWindowManyResponse{
		Entries: entries,
	}), nil
}

// GetTopMany implements the GetTopMany RPC.
func (s *TopProductsServiceServer) GetTopMany(ctx context.Context, req *connect.Request[pb.GetTopManyRequest]) (*connect.Response[pb.GetTopManyResponse], error) {
	msg := req.Msg
	if len(msg.CategoryIds) == 0 {
		return nil, connect.NewError(connect.CodeInvalidArgument, fmt.Errorf("category_ids is required"))
	}
	keys := make([]string, len(msg.CategoryIds))
	for i, v := range msg.CategoryIds {
		keys[i] = fmt.Sprintf("category:%s", v)
	}
	values, present, err := s.client.GetMany(ctx, keys)
	if err != nil {
		return nil, connect.NewError(connect.CodeInternal, err)
	}
	entries := make([]*pb.TopKItemList, len(values))
	for i, v := range values {
		items := make([]*pb.TopKItem, len(v))
		for j, it := range v {
			items[j] = &pb.TopKItem{Key: it.Key, Count: int64(it.Count)}
		}
		entries[i] = &pb.TopKItemList{Items: items}
	}
	return connect.NewResponse(&pb.GetTopManyResponse{
		Entries: entries,
		Present: present,
	}), nil
}

// GetTopRange implements the GetTopRange RPC.
func (s *TopProductsServiceServer) GetTopRange(ctx context.Context, req *connect.Request[pb.GetTopRangeRequest]) (*connect.Response[pb.GetTopRangeResponse], error) {
	msg := req.Msg
	if strings.TrimSpace(msg.CategoryId) == "" {
		return nil, connect.NewError(connect.CodeInvalidArgument, fmt.Errorf("category_id is required"))
	}
	key := fmt.Sprintf("category:%s", msg.CategoryId)
	start := time.Unix(msg.StartUnix, 0)
	end := time.Unix(msg.EndUnix, 0)
	val, err := s.client.GetRange(ctx, key, start, end)
	if err != nil {
		return nil, connect.NewError(connect.CodeInternal, err)
	}
	items := make([]*pb.TopKItem, len(val))
	for i, it := range val {
		items[i] = &pb.TopKItem{Key: it.Key, Count: int64(it.Count)}
	}
	return connect.NewResponse(&pb.GetTopRangeResponse{
		Items: items,
	}), nil
}
