// Code generated by murmur-codegen-typed. DO NOT EDIT.
// Source: pipeline-spec for service RecentVisitorsService.

package v1

import (
	"context"
	"fmt"
	"strings"
	"time"

	"connectrpc.com/connect"

	"github.com/gallowaysoftware/murmur/pkg/query/typed"
	"github.com/gallowaysoftware/murmur/proto/gen/murmur/v1/murmurv1connect"

	pb "github.com/example/marketing/gen/visitors/v1"
)

// RecentVisitorsServiceServer is the typed Connect-RPC server for the
// "visitors_bloom" Murmur pipeline.
type RecentVisitorsServiceServer struct {
	client *typed.BloomClient
}

// NewRecentVisitorsServiceServer constructs the server given a Connect-RPC
// client to the Murmur QueryService backing the
// "visitors_bloom" pipeline.
func NewRecentVisitorsServiceServer(murmur murmurv1connect.QueryServiceClient) *RecentVisitorsServiceServer {
	return &RecentVisitorsServiceServer{
		client: typed.NewBloomClient(murmur),
	}
}

// GetFilterShape implements the GetFilterShape RPC.
func (s *RecentVisitorsServiceServer) GetFilterShape(ctx context.Context, req *connect.Request[pb.GetFilterShapeRequest]) (*connect.Response[pb.GetFilterShapeResponse], error) {
	msg := req.Msg
	if strings.TrimSpace(msg.CampaignId) == "" {
		return nil, connect.NewError(connect.CodeInvalidArgument, fmt.Errorf("campaign_id is required"))
	}
	key := fmt.Sprintf("campaign:%s", msg.CampaignId)
	val, present, err := s.client.Get(ctx, key)
	if err != nil {
		return nil, connect.NewError(connect.CodeInternal, err)
	}
	return connect.NewResponse(&pb.GetFilterShapeResponse{
		CapacityBits:  int64(val.CapacityBits),
		HashFunctions: int32(val.HashFunctions),
		ApproxSize:    int64(val.ApproxSize),
		Present:       present,
	}), nil
}
