// Code generated by murmur-codegen-typed. DO NOT EDIT.
// Source: pipeline-spec for service RecentVisitorsService.

package v1

import (
	"context"
	"fmt"
	"strings"
	"time"

	"connectrpc.com/connect"

	"github.com/gallowaysoftware/murmur/pkg/query/typed"
	"github.com/gallowaysoftware/murmur/proto/gen/murmur/v1/murmurv1connect"

	pb "github.com/example/marketing/gen/visitors/v1"
)

// RecentVisitorsServiceServer is the typed Connect-RPC server for the
// "visitors_bloom" Murmur pipeline.
type RecentVisitorsServiceServer struct {
	client *typed.BloomClient
}

// NewRecentVisitorsServiceServer constructs the server given a Connect-RPC
// client to the Murmur QueryService backing the
// "visitors_bloom" pipeline.
func NewRecentVisitorsServiceServer(murmur murmurv1connect.QueryServiceClient) *RecentVisitorsServiceServer {
	return &RecentVisitorsServiceServer{
		client: typed.NewBloomClient(murmur),
	}
}

// GetFilterShape implements the GetFilterShape RPC.
func (s *RecentVisitorsServiceServer) GetFilterShape(ctx context.Context, req *connect.Request[pb.GetFilterShapeRequest]) (*connect.Response[pb.GetFilterShapeResponse], error) {
	msg := req.Msg
	if strings.TrimSpace(msg.CampaignId) == "" {
		return nil, connect.NewError(connect.CodeInvalidArgument, fmt.Errorf("campaign_id is required"))
	}
	key := fmt.Sprintf("campaign:%s", msg.CampaignId)
	val, present, err := s.client.Get(ctx, key)
	if err != nil {
		return nil, connect.NewError(connect.CodeInternal, err)
	}
	return connect.NewResponse(&pb.GetFilterShapeResponse{
		CapacityBits:  int64(val.CapacityBits),
		HashFunctions: int32(val.HashFunctions),
		ApproxSize:    int64(val.ApproxSize),
		Present:       present,
	}), nil
}

// GetFilterShapeWindowMany implements the GetFilterShapeWindowMany RPC.
func (s *RecentVisitorsServiceServer) GetFilterShapeWindowMany(ctx context.Context, req *connect.Request[pb.GetFilterShapeWindowManyRequest]) (*connect.Response[pb.GetFilterShapeWindowManyResponse], error) {
	msg := req.Msg
	if len(msg.CampaignIds) == 0 {
		return nil, connect.NewError(connect.CodeInvalidArgument, fmt.Errorf("campaign_ids is required"))
	}
	duration := time.Duration(msg.DurationSeconds) * time.Second
	keys := make([]string, len(msg.CampaignIds))
	for i, v := range msg.CampaignIds {
		keys[i] = fmt.Sprintf("campaign:%s", v)
	}
	values, err := s.client.GetWindowMany(ctx, keys, duration)
	if err != nil {
		return nil, connect.NewError(connect.CodeInternal, err)
	}
	entries := make([]*pb.BloomShape, len(values))
	for i, v := range values {
		entries[i] = &pb.BloomShape{
			CapacityBits:  int64(v.CapacityBits),
			HashFunctions: int32(v.HashFunctions),
			ApproxSize:    int64(v.ApproxSize),
		}
	}
	return connect.NewResponse(&pb.GetFilterShapeWindowManyResponse{
		Entries: entries,
	}), nil
}
