package main

import (
	"bytes"
	"fmt"
	"path"
	"strings"
	"text/template"
)

// renderProto emits the .proto file for the given Spec.
//
// Response message shape varies by pipeline kind:
//
//	sum   → { int64 value, bool present }
//	hll   → { int64 value, bool present } (value is the cardinality)
//	topk  → { repeated TopKItem items, bool present }
//	bloom → { int64 capacity_bits, int32 hash_functions, int64 approx_size, bool present }
//
// TopK pipelines emit a `TopKItem` message at the top of the proto so
// the response can reference it.
func renderProto(s *Spec) ([]byte, error) {
	t, err := template.New("proto").Funcs(template.FuncMap{
		"protoFieldType": protoFieldType,
		"plus1":          func(i int) int { return i + 1 },
		"responseBody":   responseBody,
		"goPackageShort": goPackageShort,
		"isTopK":         func(k PipelineKind) bool { return k == PipelineTopK },
	}).Parse(protoTemplate)
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	if err := t.Execute(&buf, s); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

const protoTemplate = `// Code generated by murmur-codegen-typed. DO NOT EDIT.
// Source: pipeline-spec for service {{.Service.Name}}.

syntax = "proto3";

package {{.ProtoPackage}};

option go_package = "{{.ProtoGoPackage}};{{goPackageShort .ProtoGoPackage}}";

{{if isTopK .Service.PipelineKind}}
// TopKItem is one (key, count) pair from a Misra-Gries Top-K summary.
message TopKItem {
  string key = 1;
  int64 count = 2;
}
{{end}}
{{range .Service.Methods}}
message {{.Name}}Request {
{{range $i, $f := .Request}}  {{protoFieldType $f.Type}} {{$f.Name}} = {{plus1 $i}};
{{end}}}

message {{.Name}}Response {
{{responseBody $.Service.PipelineKind}}}
{{end}}
service {{.Service.Name}} {
{{range .Service.Methods}}  rpc {{.Name}}({{.Name}}Request) returns ({{.Name}}Response);
{{end}}}
`

// protoFieldType maps spec types to proto types.
func protoFieldType(t string) string {
	switch t {
	case "string":
		return "string"
	case "int64":
		return "int64"
	case "repeated string":
		return "repeated string"
	default:
		return fmt.Sprintf("/* unsupported type %q */ string", t)
	}
}

// responseBody returns the proto-field block for a Response message,
// per pipeline kind. The block is indented and includes the trailing
// newline before the closing brace; the template wraps it with
// `message Foo { ... }`.
func responseBody(k PipelineKind) string {
	switch k {
	case PipelineSum, PipelineHLL:
		return "  int64 value = 1;\n  bool present = 2;\n"
	case PipelineTopK:
		return "  repeated TopKItem items = 1;\n  bool present = 2;\n"
	case PipelineBloom:
		return "  int64 capacity_bits = 1;\n  int32 hash_functions = 2;\n  int64 approx_size = 3;\n  bool present = 4;\n"
	default:
		return "  // unsupported pipeline kind\n  bool present = 1;\n"
	}
}

// goPackageShort returns the package alias for the go_package option:
// "github.com/x/y/v1" → "v1". Mirrors buf's default behavior.
func goPackageShort(p string) string {
	if p == "" {
		return "pb"
	}
	last := path.Base(p)
	last = strings.TrimLeft(last, ".")
	if last == "" {
		return "pb"
	}
	return last
}
