package main

import (
	"bytes"
	"fmt"
	"path"
	"strings"
	"text/template"
)

// renderProto emits the .proto file for the given Spec.
//
// Layout: one request and one response message per method, then
// the service definition. Field numbers for request fields follow
// declaration order; response is { value(int64) | cardinality(int64),
// present bool }.
//
// We deliberately do NOT use the proto-generator framework or
// protobuf.proto descriptors — text/template emits cleaner output
// and the schema is small enough that template churn is fine.
func renderProto(s *Spec) ([]byte, error) {
	t, err := template.New("proto").Funcs(template.FuncMap{
		"protoFieldType": protoFieldType,
		"plus1":          func(i int) int { return i + 1 },
		"responseField":  responseFieldName,
		"goPackageShort": goPackageShort,
	}).Parse(protoTemplate)
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	if err := t.Execute(&buf, s); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

const protoTemplate = `// Code generated by murmur-codegen-typed. DO NOT EDIT.
// Source: pipeline-spec for service {{.Service.Name}}.

syntax = "proto3";

package {{.ProtoPackage}};

option go_package = "{{.ProtoGoPackage}};{{goPackageShort .ProtoGoPackage}}";

{{range .Service.Methods}}
message {{.Name}}Request {
{{range $i, $f := .Request}}  {{protoFieldType $f.Type}} {{$f.Name}} = {{plus1 $i}};
{{end}}}

message {{.Name}}Response {
  {{responseField $.Service.PipelineKind}} value = 1;
  bool present = 2;
}
{{end}}
service {{.Service.Name}} {
{{range .Service.Methods}}  rpc {{.Name}}({{.Name}}Request) returns ({{.Name}}Response);
{{end}}}
`

// protoFieldType maps spec types to proto types.
func protoFieldType(t string) string {
	switch t {
	case "string":
		return "string"
	case "int64":
		return "int64"
	case "repeated string":
		return "repeated string"
	default:
		return fmt.Sprintf("/* unsupported type %q */ string", t)
	}
}

// responseFieldName returns the name of the value field for the
// given pipeline kind. Sum pipelines return int64; HLL pipelines
// return int64 (cardinality). Both shapes use field number 1 with
// the type baked in.
func responseFieldName(k PipelineKind) string {
	switch k {
	case PipelineSum:
		return "int64"
	case PipelineHLL:
		return "int64"
	default:
		return "int64"
	}
}

// goPackageShort returns the package alias for the go_package option:
// "github.com/x/y/v1" → "v1". Mirrors buf's default behavior.
func goPackageShort(p string) string {
	if p == "" {
		return "pb"
	}
	last := path.Base(p)
	// Strip leading dots and special chars.
	last = strings.TrimLeft(last, ".")
	if last == "" {
		return "pb"
	}
	return last
}
