package main

import (
	"bytes"
	"fmt"
	"path"
	"strings"
	"text/template"
)

// renderServer emits the Go server stub for the given Spec.
//
// Imports the buf-generated proto types from Spec.ProtoGoPackage; the
// user must run buf (or protoc) before the stub will compile.
//
// Per-kind response assembly:
//   - sum   → response.Value = val
//   - hll   → response.Value = int64(val.Cardinality)
//   - topk  → response.Items built from []typed.TopKItem
//   - bloom → response fields populated from typed.BloomValue
func renderServer(s *Spec) ([]byte, error) {
	t, err := template.New("server").Funcs(template.FuncMap{
		"goFieldName":     goFieldName,
		"renderKey":       renderKeyTemplate,
		"clientType":      clientType,
		"clientCtor":      clientCtor,
		"buildResponse":   buildResponse,
		"goPkgName":       goPkgName,
		"protoPkgAlias":   protoPkgAlias,
		"isTopK":          func(k PipelineKind) bool { return k == PipelineTopK },
		"emitTopKImports": func(k PipelineKind) bool { return k == PipelineTopK },
	}).Parse(serverTemplate)
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	if err := t.Execute(&buf, s); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

const serverTemplate = `// Code generated by murmur-codegen-typed. DO NOT EDIT.
// Source: pipeline-spec for service {{.Service.Name}}.

package {{goPkgName .GoPackage}}

import (
	"context"
	"fmt"
	"strings"
	"time"

	"connectrpc.com/connect"

	"github.com/gallowaysoftware/murmur/pkg/query/typed"
	"github.com/gallowaysoftware/murmur/proto/gen/murmur/v1/murmurv1connect"

	pb "{{.ProtoGoPackage}}"
)

// {{.Service.Name}}Server is the typed Connect-RPC server for the
// "{{.Service.PipelineName}}" Murmur pipeline.
type {{.Service.Name}}Server struct {
	client *typed.{{clientType .Service.PipelineKind}}
}

// New{{.Service.Name}}Server constructs the server given a Connect-RPC
// client to the Murmur QueryService backing the
// "{{.Service.PipelineName}}" pipeline.
func New{{.Service.Name}}Server(murmur murmurv1connect.QueryServiceClient) *{{.Service.Name}}Server {
	return &{{.Service.Name}}Server{
		client: typed.{{clientCtor .Service.PipelineKind}}(murmur),
	}
}

{{range $m := .Service.Methods}}
// {{$m.Name}} implements the {{$m.Name}} RPC.
func (s *{{$.Service.Name}}Server) {{$m.Name}}(ctx context.Context, req *connect.Request[pb.{{$m.Name}}Request]) (*connect.Response[pb.{{$m.Name}}Response], error) {
	msg := req.Msg
{{- range $f := $m.Request}}
{{- if eq $f.Type "string"}}
	if strings.TrimSpace(msg.{{goFieldName $f.Name}}) == "" {
		return nil, connect.NewError(connect.CodeInvalidArgument, fmt.Errorf("{{$f.Name}} is required"))
	}
{{- end}}
{{- end}}
	key := {{renderKey $m}}
{{- if eq $m.Kind "get_all_time"}}
	val, present, err := s.client.Get(ctx, key)
	if err != nil {
		return nil, connect.NewError(connect.CodeInternal, err)
	}
{{buildResponse $.Service.PipelineKind $m.Name "val" "present"}}
{{- else if eq $m.Kind "get_window"}}
	duration := time.Duration(msg.{{goFieldName $m.WindowDurationField}}) * time.Second
{{- if or (eq $.Service.PipelineKind "sum") (eq $.Service.PipelineKind "hll")}}
	val, err := s.client.GetWindow(ctx, key, duration)
{{- else}}
	val, err := s.client.GetWindow(ctx, key, duration)
{{- end}}
	if err != nil {
		return nil, connect.NewError(connect.CodeInternal, err)
	}
{{buildResponse $.Service.PipelineKind $m.Name "val" "true"}}
{{- end}}
}
{{end}}
`

// goFieldName converts snake_case to CamelCase as protoc-go does for
// field names (bot_id → BotId, duration_seconds → DurationSeconds).
func goFieldName(s string) string {
	parts := strings.Split(s, "_")
	for i, p := range parts {
		if p == "" {
			continue
		}
		parts[i] = strings.ToUpper(p[:1]) + p[1:]
	}
	return strings.Join(parts, "")
}

// renderKeyTemplate emits the Go expression that builds the entity
// key from the request message fields. KeyTemplate
// "bot:{bot_id}|user:{user_id}" → fmt.Sprintf("bot:%s|user:%s", msg.BotId, msg.UserId).
func renderKeyTemplate(m Method) string {
	refs := templateRefs(m.KeyTemplate)
	formatStr := m.KeyTemplate
	args := make([]string, 0, len(refs))
	for _, ref := range refs {
		f := findField(m.Request, ref)
		if f == nil {
			continue
		}
		var verb string
		switch f.Type {
		case "int64":
			verb = "%d"
		default:
			verb = "%s"
		}
		formatStr = strings.Replace(formatStr, "{"+ref+"}", verb, 1)
		args = append(args, "msg."+goFieldName(ref))
	}
	if len(args) == 0 {
		return fmt.Sprintf("%q", formatStr)
	}
	return fmt.Sprintf("fmt.Sprintf(%q, %s)", formatStr, strings.Join(args, ", "))
}

// clientType returns the typed-client type name in pkg/query/typed
// for the given pipeline kind.
func clientType(k PipelineKind) string {
	switch k {
	case PipelineSum:
		return "SumClient"
	case PipelineHLL:
		return "HLLClient"
	case PipelineTopK:
		return "TopKClient"
	case PipelineBloom:
		return "BloomClient"
	default:
		return "Client"
	}
}

// clientCtor returns the constructor function name in pkg/query/typed
// for the given pipeline kind.
func clientCtor(k PipelineKind) string {
	switch k {
	case PipelineSum:
		return "NewSumClient"
	case PipelineHLL:
		return "NewHLLClient"
	case PipelineTopK:
		return "NewTopKClient"
	case PipelineBloom:
		return "NewBloomClient"
	default:
		return "NewClient"
	}
}

// buildResponse returns the Go statement(s) that construct and return
// the response for a method, per pipeline kind. The varName is the
// local holding the typed-client result (e.g. "val"); presentExpr is
// either "present" (a local variable name) or "true" (a literal —
// GetWindow doesn't return a present flag in the typed-client surface).
//
// The output is the closing portion of a method body (the indentation
// is fixed at one tab — the template emits this verbatim after
// "if err != nil { … }").
func buildResponse(k PipelineKind, methodName, varName, presentExpr string) string {
	respType := "pb." + methodName + "Response"
	switch k {
	case PipelineSum:
		return fmt.Sprintf(`	return connect.NewResponse(&%s{
		Value:   %s,
		Present: %s,
	}), nil`, respType, varName, presentExpr)
	case PipelineHLL:
		return fmt.Sprintf(`	return connect.NewResponse(&%s{
		Value:   int64(%s.Cardinality),
		Present: %s,
	}), nil`, respType, varName, presentExpr)
	case PipelineTopK:
		// TopK results from typed.TopKClient are []typed.TopKItem; we
		// have to translate to []*pb.TopKItem.
		return fmt.Sprintf(`	items := make([]*pb.TopKItem, len(%s))
	for i, it := range %s {
		items[i] = &pb.TopKItem{Key: it.Key, Count: int64(it.Count)}
	}
	return connect.NewResponse(&%s{
		Items:   items,
		Present: %s,
	}), nil`, varName, varName, respType, presentExpr)
	case PipelineBloom:
		return fmt.Sprintf(`	return connect.NewResponse(&%s{
		CapacityBits:  int64(%s.CapacityBits),
		HashFunctions: int32(%s.HashFunctions),
		ApproxSize:    int64(%s.ApproxSize),
		Present:       %s,
	}), nil`, respType, varName, varName, varName, presentExpr)
	default:
		return fmt.Sprintf(`	return connect.NewResponse(&%s{Present: %s}), nil`, respType, presentExpr)
	}
}

// goPkgName returns the package name for the generated Go file from
// the GoPackage import path. "github.com/x/y/botv1" → "botv1".
func goPkgName(p string) string {
	if p == "" {
		return "pb"
	}
	return path.Base(p)
}

// protoPkgAlias returns the alias under which the generated Go server
// stub imports the buf-generated proto types. We always import as `pb`
// for consistency.
func protoPkgAlias(p string) string {
	return "pb"
}
