package main

import (
	"bytes"
	"fmt"
	"path"
	"strings"
	"text/template"
)

// renderServer emits the Go server stub for the given Spec. The output
// imports the buf-generated proto types from Spec.ProtoGoPackage; the
// user must run buf (or protoc) before the stub will compile.
func renderServer(s *Spec) ([]byte, error) {
	t, err := template.New("server").Funcs(template.FuncMap{
		"goFieldName":      goFieldName,
		"renderKey":        renderKeyTemplate,
		"clientType":       clientType,
		"clientCtor":       clientCtor,
		"valueFieldOnResp": valueFieldOnResp,
		"goPkgName":        goPkgName,
		"protoPkgAlias":    protoPkgAlias,
	}).Parse(serverTemplate)
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	if err := t.Execute(&buf, s); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

const serverTemplate = `// Code generated by murmur-codegen-typed. DO NOT EDIT.
// Source: pipeline-spec for service {{.Service.Name}}.

package {{goPkgName .GoPackage}}

import (
	"context"
	"fmt"
	"strings"
	"time"

	"connectrpc.com/connect"

	"github.com/gallowaysoftware/murmur/pkg/query/typed"
	"github.com/gallowaysoftware/murmur/proto/gen/murmur/v1/murmurv1connect"

	pb "{{.ProtoGoPackage}}"
)

// {{.Service.Name}}Server is the typed Connect-RPC server for the
// "{{.Service.PipelineName}}" Murmur pipeline.
type {{.Service.Name}}Server struct {
	client *typed.{{clientType .Service.PipelineKind}}
}

// New{{.Service.Name}}Server constructs the server given a Connect-RPC
// client to the Murmur QueryService backing the
// "{{.Service.PipelineName}}" pipeline.
func New{{.Service.Name}}Server(murmur murmurv1connect.QueryServiceClient) *{{.Service.Name}}Server {
	return &{{.Service.Name}}Server{
		client: typed.{{clientCtor .Service.PipelineKind}}(murmur),
	}
}

{{range $m := .Service.Methods}}
// {{$m.Name}} implements the {{$m.Name}} RPC.
func (s *{{$.Service.Name}}Server) {{$m.Name}}(ctx context.Context, req *connect.Request[pb.{{$m.Name}}Request]) (*connect.Response[pb.{{$m.Name}}Response], error) {
	msg := req.Msg
{{- range $f := $m.Request}}
{{- if eq $f.Type "string"}}
	if strings.TrimSpace(msg.{{goFieldName $f.Name}}) == "" {
		return nil, connect.NewError(connect.CodeInvalidArgument, fmt.Errorf("{{$f.Name}} is required"))
	}
{{- end}}
{{- end}}
	key := {{renderKey $m}}
{{- if eq $m.Kind "get_all_time"}}
	val, present, err := s.client.Get(ctx, key)
	if err != nil {
		return nil, connect.NewError(connect.CodeInternal, err)
	}
	return connect.NewResponse(&pb.{{$m.Name}}Response{
		Value:   {{valueFieldOnResp $.Service.PipelineKind "val"}},
		Present: present,
	}), nil
{{- else if eq $m.Kind "get_window"}}
	duration := time.Duration(msg.{{goFieldName $m.WindowDurationField}}) * time.Second
	val, present, err := s.client.GetWindow(ctx, key, duration)
	if err != nil {
		return nil, connect.NewError(connect.CodeInternal, err)
	}
	return connect.NewResponse(&pb.{{$m.Name}}Response{
		Value:   {{valueFieldOnResp $.Service.PipelineKind "val"}},
		Present: present,
	}), nil
{{- end}}
}
{{end}}
`

// goFieldName converts snake_case to CamelCase as protoc-go-go does
// for field names (bot_id → BotId, duration_seconds → DurationSeconds).
func goFieldName(s string) string {
	parts := strings.Split(s, "_")
	for i, p := range parts {
		if p == "" {
			continue
		}
		parts[i] = strings.ToUpper(p[:1]) + p[1:]
	}
	return strings.Join(parts, "")
}

// renderKeyTemplate emits the Go expression that builds the entity
// key from the request message fields. KeyTemplate
// "bot:{bot_id}|user:{user_id}" → fmt.Sprintf("bot:%s|user:%s", msg.BotId, msg.UserId).
func renderKeyTemplate(m Method) string {
	refs := templateRefs(m.KeyTemplate)
	// Replace {x} with %s (or %d for int types).
	formatStr := m.KeyTemplate
	args := make([]string, 0, len(refs))
	for _, ref := range refs {
		f := findField(m.Request, ref)
		if f == nil {
			continue
		}
		var verb string
		switch f.Type {
		case "int64":
			verb = "%d"
		default:
			verb = "%s"
		}
		formatStr = strings.Replace(formatStr, "{"+ref+"}", verb, 1)
		args = append(args, "msg."+goFieldName(ref))
	}
	if len(args) == 0 {
		// No interpolation — template was a literal string.
		return fmt.Sprintf("%q", formatStr)
	}
	return fmt.Sprintf("fmt.Sprintf(%q, %s)", formatStr, strings.Join(args, ", "))
}

// clientType returns the typed client type name in pkg/query/typed
// for the given pipeline kind. PipelineSum → "SumClient", etc.
func clientType(k PipelineKind) string {
	switch k {
	case PipelineSum:
		return "SumClient"
	case PipelineHLL:
		return "HLLClient"
	default:
		return "Client"
	}
}

// clientCtor returns the constructor name in pkg/query/typed for
// the given pipeline kind.
func clientCtor(k PipelineKind) string {
	switch k {
	case PipelineSum:
		return "NewSumClient"
	case PipelineHLL:
		return "NewHLLClient"
	default:
		return "NewClient"
	}
}

// valueFieldOnResp returns the expression for the Value field on the
// response message, given a Go variable name holding the typed-client
// result. Sum returns int64, HLL returns HLLValue{Cardinality, ByteLen}.
func valueFieldOnResp(k PipelineKind, varname string) string {
	switch k {
	case PipelineSum:
		return varname
	case PipelineHLL:
		// HLLValue.Cardinality is uint64; proto field is int64.
		return fmt.Sprintf("int64(%s.Cardinality)", varname)
	default:
		return varname
	}
}

// goPkgName returns the package name for the generated Go file from
// the GoPackage import path. "github.com/x/y/botv1" → "botv1".
func goPkgName(p string) string {
	if p == "" {
		return "pb"
	}
	return path.Base(p)
}

// protoPkgAlias returns the alias under which the generated Go server
// stub imports the buf-generated proto types. We always import as `pb`
// for consistency.
func protoPkgAlias(p string) string {
	return "pb"
}
